INSERT INTO `laws` (`name`, `title`) VALUES ('sin', 'Синусоидальный');
INSERT INTO `laws` (`name`, `title`) VALUES ('linear', 'Линейный');
INSERT INTO `laws` (`name`, `title`) VALUES ('saw', 'Пилообразный');
INSERT INTO `laws` (`name`, `title`) VALUES ('ln', 'Логарифмический');
INSERT INTO `laws` (`name`, `title`) VALUES ('ln-1', 'Обратный логарифмический');
INSERT INTO `laws` (`name`, `title`) VALUES ('ln-1*sin', 'Синусоидальный, логарифмически убывающий');
INSERT INTO `laws` (`name`, `title`) VALUES ('ln*sin', 'Синусоидальный, логарифмически возрастающий');
INSERT INTO `laws` (`name`, `title`) VALUES ('linear-1*sin', 'Синусоидальный, линейно убывающий');
INSERT INTO `laws` (`name`, `title`) VALUES ('linear*sin', 'Синусоидальный, линейно возрастающий');
INSERT INTO `laws` (`name`, `title`) VALUES ('const', 'Постоянный');
