INSERT INTO `laws` (`name`, `title`) VALUES ('linear_congruential_engine', 'Linear congruential random number engine');
INSERT INTO `laws` (`name`, `title`) VALUES ('mersenne_twister_engine', 'Mersenne twister random number engine');
INSERT INTO `laws` (`name`, `title`) VALUES ('subtract_with_carry_engine', 'Subtract-with-carry random number engine');
INSERT INTO `laws` (`name`, `title`) VALUES ('discard_block_engine', 'Discard-block random number engine adaptor');
INSERT INTO `laws` (`name`, `title`) VALUES ('independent_bits_engine', 'Independent-bits random number engine adaptor');
INSERT INTO `laws` (`name`, `title`) VALUES ('shuffle_order_engine', 'Shuffle-order random number engine adaptor');
INSERT INTO `laws` (`name`, `title`) VALUES ('default_random_engine', 'Default random engine');
INSERT INTO `laws` (`name`, `title`) VALUES ('minstd_rand', 'Minimal Standard minstd_rand generator');
INSERT INTO `laws` (`name`, `title`) VALUES ('minstd_rand0', 'Minimal Standard minstd_rand0 generator');
INSERT INTO `laws` (`name`, `title`) VALUES ('mt19937', 'Mersenne Twister 19937 generator');
INSERT INTO `laws` (`name`, `title`) VALUES ('mt19937_64', 'Mersene Twister 19937 generator (64 bit)');
INSERT INTO `laws` (`name`, `title`) VALUES ('ranlux24_base', 'Ranlux 24 base generator');
INSERT INTO `laws` (`name`, `title`) VALUES ('ranlux48_base', 'Ranlux 48 base generator');
INSERT INTO `laws` (`name`, `title`) VALUES ('ranlux24', 'Ranlux 24 generator');
INSERT INTO `laws` (`name`, `title`) VALUES ('ranlux48', 'Ranlux 48 generator');
INSERT INTO `laws` (`name`, `title`) VALUES ('knuth_b', 'Knuth-B generator');
INSERT INTO `laws` (`name`, `title`) VALUES ('random_device', 'True random number generator');
INSERT INTO `laws` (`name`, `title`) VALUES ('uniform_int_distribution', 'Uniform discrete distribution');
INSERT INTO `laws` (`name`, `title`) VALUES ('uniform_real_distribution', 'Uniform real distribution');
INSERT INTO `laws` (`name`, `title`) VALUES ('bernoulli_distribution', 'Bernoulli distribution');
INSERT INTO `laws` (`name`, `title`) VALUES ('binomial_distribution', 'Binomial distribution');
INSERT INTO `laws` (`name`, `title`) VALUES ('geometric_distribution', 'Geometric distribution');
INSERT INTO `laws` (`name`, `title`) VALUES ('negative_binomial_distribution', 'Negative binomial distribution');
INSERT INTO `laws` (`name`, `title`) VALUES ('poisson_distribution', 'Poisson distribution');
INSERT INTO `laws` (`name`, `title`) VALUES ('exponential_distribution', 'Exponential distribution');
INSERT INTO `laws` (`name`, `title`) VALUES ('gamma_distribution', 'Gamma distribution');
INSERT INTO `laws` (`name`, `title`) VALUES ('weibull_distribution', 'Weibull distribution');
INSERT INTO `laws` (`name`, `title`) VALUES ('extreme_value_distribution', 'Extreme Value distribution');
INSERT INTO `laws` (`name`, `title`) VALUES ('normal_distribution', 'Normal distribution');
INSERT INTO `laws` (`name`, `title`) VALUES ('lognormal_distribution', 'Lognormal distribution');
INSERT INTO `laws` (`name`, `title`) VALUES ('chi_squared_distribution', 'Chi-squared distribution');
INSERT INTO `laws` (`name`, `title`) VALUES ('cauchy_distribution', 'Cauchy distribution');
INSERT INTO `laws` (`name`, `title`) VALUES ('fisher_f_distribution', 'Fisher F-distribution');
INSERT INTO `laws` (`name`, `title`) VALUES ('student_t_distribution', 'Student T-Distribution');
INSERT INTO `laws` (`name`, `title`) VALUES ('discrete_distribution', 'Discrete distribution');
INSERT INTO `laws` (`name`, `title`) VALUES ('piecewise_constant_distribution', 'Piecewise constant distribution');
INSERT INTO `laws` (`name`, `title`) VALUES ('piecewise_linear_distribution', 'Piecewise linear distribution');
INSERT INTO `laws` (`name`, `title`) VALUES ('seed_seq', 'Seed sequence');
INSERT INTO `laws` (`name`, `title`) VALUES ('generate_canonical', 'Generate canonical numbers');

